### ISSUE TITLE
K2 and K2E compatibility issue

### ISSUE THREAD

**Issue by Val3ri0** [CecilieBrandt/K2StructuralRepo#3]
Hi Cecilie,

I'm experiencing an issue with the Kangaroo Solver when testing the Grisdshell example.

I'm having the same issue other users have reported on the Grasshopper forum:
https://www.grasshopper3d.com/group/kangaroo/forum/topics/k2engineering-goals-cannot-be-converted

I'm using Rhino 6.

I've tried reinstalling Kangaroo but with no success.

Any help would be very appreciated.

**Comment by habibamoubarak** [comment]
Hey Valerio
The problem is that your kangaroo dll library is existing in two places as it is now automatically downloaded when you get grasshopper, plus the other local file you create with all the other plugins.  Grasshopper gets confused as to which one to refer to. I had the same problem and fixed it by removing the embedded dll file from the folder with grasshopper downloaded, and left a single version with my other plugins.

**Comment by Val3ri0** [comment]
Hi habibamoubarak

Many thanks for your help, I tried searching for any kangaroo.dll I have on my computer but the only one I can find is in the Grasshopper Libraries folder.
Is there another kangaroo.dll saved somewhere with the grasshopper part of the Rhino  6 package?
Where can I find it?

> Hey Valerio
> The problem is that your kangaroo dll library is existing in two places as it is now automatically downloaded when you get grasshopper, plus the other local file you create with all the other plugins. Grasshopper gets confused as to which one to refer to. I had the same problem and fixed it by removing the embedded dll file from the folder with grasshopper downloaded, and left a single version with my other plugins.

**Comment by CecilieBrandt** [comment]
Hi Val3ri0,

As Habiba mentions, Kangaroo2 is now a native part of Grasshopper with Rhino 6. It is installed here:
C:\Program Files\Rhino 6\Plug-ins\Grasshopper\Components

Your previous gha files are most likely located here:
C:\Users\nameXX\AppData\Roaming\Grasshopper\Libraries

Try to delete the Kangaroo2 gha and dll in the last folder and see if that solves the problem?
