### ISSUE TITLE
Example of Loading Cases

### ISSUE THREAD

**Issue by timothytai** [CecilieBrandt/K2StructuralRepo#5]
Hi Cecilie,

Firstly, thanks for the great plugin! Might you be able to provide some examples regarding (1) pretension and (2) load cases? I had gone through the four example files but could not find demos of when MeshSelfWeight, MeshWindLoad, and MeshSnowLoad components are used. Specifically, what might be a good workflow to obtain the list of values to be input into "nA" in these three nodes. I can of course guess at how they should be put together based on gh experience, but it would be very nice to confirm that they are used correctly. Thanks a lot!

**Comment by CecilieBrandt** [comment]
Hi Timothy,

Yes of course. I think the cablenet example is the best one to demonstrate the use of pretension and load cases.

**1. Pretension**
The cablenet example only includes pretension at the moment. The idea is then that you apply the external load in the analysis step to see how the cablenet performs under a given pretension distribution. The point is that this pretension distribution is directly related to the form-finding of the cablenet so you cannot seperate form-finding and analysis. The effect of this is that you get zero displacement between the form-found shape and the pretensioned shape in the analysis step (which is what you want). See attached screenshot.

![Cablenet_prestress](https://user-images.githubusercontent.com/5569946/56468272-5e006900-642a-11e9-9312-0f20572d9811.png)

You will notice that the max pretension value that you specify for the distribution will also be the max axial force you can extract from the results. If you input any other distribution or constant value into the pretension input, the shape will start to deviate from the form-found shape.

**2. Load cases**
The value of the pretension becomes clear when you apply external loads. The pretension helps to control the deflections, however it is at the cost of bigger axial forces and reactions. So you have to balance the two. In K2E it is only possible to run a simulation for one load case at a time. See attached screenshot for how you can define your load cases and use the load components in K2E.

![Cablenet_prestress_and_external_forces](https://user-images.githubusercontent.com/5569946/56468276-72dcfc80-642a-11e9-81ed-e6003dcc4724.png)

**Comment by timothytai** [comment]
Hi Cecilie,

Thank you very much for this helpful response. Two subsequent questions:
(1) May you please add an option to project to planes other than XY such as XZ and YZ in the MeshVertexArea component? We tried to modify the code on the most superficial level by changing the `projectMeshToXY()` implementation to the other two planes and the `calcVertexVoronoiAreas()` function seems to no longer work.
This would be helpful for different wind cases in addition to the original intend for snow load.
(2) Should the force calculation in your implementation of the wind load component be:
```
If (scale)
{
    force = wDir * dotProduct * vertex area * w *10^3
}
```
Thanks again.

**Comment by CecilieBrandt** [comment]
1. Yes, that makes a lot of sense to have the option to project to the XZ and YZ plane as well. I will implement that.

2. The reason why I multiply with the vertex normal direction rather than the wind direction is to make the nodal wind force act perpendicular to the mesh. You're right that sometimes that is not desirable - but it is easy to change the direction to a constant direction and use the magnitude of the force from the windload component. But I can add an option to toggle between normal direction or wind direction. I will remove the scale factor as it doesn't make much sense (it was an early attempt to approximate wind for 'unknown' cases).

I will let you know when I have updated the load components and then you can test.

**Comment by timothytai** [comment]
Thanks again for the super fast response!
I think updating the first issue will be super helpful in general - as the component can be used in other definitions to obtain tributary areas of mesh vertices while not necessarily being used together with the rest of the plugin.
For now, I thought we'd share the below screenshot of our workaround (combining both question 1 and 2):
![2019-04-22_15-13-39](https://user-images.githubusercontent.com/20776311/56520117-b0688500-6511-11e9-9c51-50ee3b6565d2.png)

**Comment by CecilieBrandt** [comment]
Thanks for sharing Timothy and I agree with you- that's why I divided the load components into separate components that calculate lengths/area, forces and then K2 specific load goal such that you can use the output for other purposes as well (not just K2E).

**Comment by CecilieBrandt** [comment]
@timothytai check out the latest release here on Github. I have updated the load components. See if that is what you were looking for.

**Comment by timothytai** [comment]
Hi Cecilie, sorry for the delayed response - thank you very much for updating the plugin!
Being able to input any plane is great. We also look forward to trying out other new components you have added in this release when we get a chance; and will reach out if we have additional questions, thanks a lot again!

**Comment by jwangax** [comment]
Hi Cecilie,
Thanks for your great explanation. I have one question regarding pretension distribution.  You explained that the benefit of using K2 factors for pretension distribution is to get the effect of "zero displacement between the form-found shape and the pre-tensioned shape in the analysis step". But in k2, the stiffness is not related to the rest length L0 of cable (pre-assigned value). In k2 engineering, the stiffness will depend on the rest length L0 of cable (L1-L0=F*L0/EA). As a result, it will not end up to be perfect "0 displacement" between the form-found shape and pre-tensioned shape.  Do you think my understanding is correct?

**Comment by CecilieBrandt** [comment]
Hi Jingwen,

You do specify a rest length for the K2 "Length" component and also a strength value. Those two values combined with the new length after form-finding are used to calculate the pretension distribution used in K2E. So to answer your question: the behaviour of the "Length" goal in K2 and the "Bar" goal in K2E is exactly the same.

**Comment by jwangax** [comment]
Hi Cecilie,
Thanks for your reply! Now I understand that the behaviour of the "Length" goal in K2 and the "Bar" / “Cable" goal in K2E are the same. They both have the stiffness (strength in K2, E/A in K2E) and length. If my understanding is correct, then the forces of elements inside K2 is proportional to (L1-L0) *EA/L0. But in the current code it is only calculated based on (L1-L0) *EA. Should it also include (/L0) part?
