### ISSUE TITLE
Not all DataTypes accessible when importing K2Engineering.gha via GHPython

### ISSUE THREAD

**Issue by fstwn** [CecilieBrandt/K2StructuralRepo#6]
Dear Cecilie,
I noticed that unfortunately not all DataTypes are accessible when importing K2Engineering in GHPython. So I just want to ask the question if this could be fixed or if it has other reasons. Your insight is much appreciated.
![Anmerkung 2019-10-02 150042](https://user-images.githubusercontent.com/13224396/66046392-f0528000-e525-11e9-87b7-79c62f87dfd3.jpg)

**Comment by CecilieBrandt** [comment]
Hi @fstwn 
Thanks for reporting this problem, it should now be fixed.

![K2E_Datatypes_Python](https://user-images.githubusercontent.com/5569946/68996682-98859380-089d-11ea-938c-454c0d36e0b2.png)
[K2Engineering_fix_191116.zip](https://github.com/CecilieBrandt/K2Engineering/files/3854470/K2Engineering_fix_191116.zip)

**Comment by fstwn** [comment]
Thank you so much! This helps a lot :-)
